// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKL9gfLAIbAgitDXKmD3Yqbc8K-R6PX3w',
    appId: '1:752747011277:web:3a929f99b8bf43963d5d84',
    messagingSenderId: '752747011277',
    projectId: 'whatsapp-backend-6632e',
    authDomain: 'whatsapp-backend-6632e.firebaseapp.com',
    storageBucket: 'whatsapp-backend-6632e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB22Q6iTm6ExGfegSX0nhO-I6AkmHCx1fE',
    appId: '1:752747011277:android:94b79497d977e0553d5d84',
    messagingSenderId: '752747011277',
    projectId: 'whatsapp-backend-6632e',
    storageBucket: 'whatsapp-backend-6632e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmFkcLKFdAwMPzUxHciat1UL0bh8gh2BA',
    appId: '1:752747011277:ios:0f042bd07087ba8f3d5d84',
    messagingSenderId: '752747011277',
    projectId: 'whatsapp-backend-6632e',
    storageBucket: 'whatsapp-backend-6632e.appspot.com',
    iosClientId: '752747011277-2lft895ml803nqaa3eft6rfh43fjgs7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmFkcLKFdAwMPzUxHciat1UL0bh8gh2BA',
    appId: '1:752747011277:ios:0f042bd07087ba8f3d5d84',
    messagingSenderId: '752747011277',
    projectId: 'whatsapp-backend-6632e',
    storageBucket: 'whatsapp-backend-6632e.appspot.com',
    iosClientId: '752747011277-2lft895ml803nqaa3eft6rfh43fjgs7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
